name = "NelderMead"
uuid = "2f6b4ddb-b4ff-44c0-b59b-2ab99302f970"
authors = ["James Cook <cookjws@gmail.com>"]
version = "0.4.0"

[compat]
julia = "1"

[extras]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Random", "Test"]
